### ISSUE TITLE
Validate event

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#10]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/client.js#L112

@dlongley this needs some explanation.

**Comment by mattcollier** [comment]
There are other TODOs on the list with this same description:

1. https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/events.js#L91
2. https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/server.js#L203

Does the same method apply equally to all of these instances?

**Comment by dlongley** [comment]
> Does the same method apply equally to all of these instances?

Yes, I believe so.
