### ISSUE TITLE
TODO: do we need `recordId`? what is it for, statistics?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#103]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/e670055ece8d1bbab42be6f86dae394c37d06cb6/lib/events.js#L850-L851

`recordId` corresponds to this index in storage:
https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/master/lib/index.js#L194

This is how the `record` API finds records.

@dlongley Does that answer your question?  Would you like a specific comment there?

**Comment by dlongley** [comment]
@mattcollier, why isn't it in `meta`?

**Comment by mattcollier** [comment]
because index fields have historically lived on the root of the document.  This is a somewhat different case than `meta.eventHash` since this is a `database.hash` (which may be the only place `database.hash` is being used these days, IDK.

Would you like to propose moving it into meta?  I have no objection.

**Comment by mattcollier** [comment]
Changing this does involve making changes to several ledger modules.

**Comment by dlongley** [comment]
Oh, I didn't realize it was a `database.hash` thing. If it's *just* database index information we don't have to change anything. The full information is in `operation.record.id`.

**Comment by mattcollier** [comment]
:)
So... about that TODO?  Shall it be removed, or should we add some documentation?

**Comment by dlongley** [comment]
Oh, please just leave a comment that says it's a database index for recordId.
