### ISSUE TITLE
Ensure that manifest.items has >= twoThirds of electors.length

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#12]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L774

TODO: must also ensure that manifest.items has >= twoThirds of
electors.length... otherwise the roll-call is insufficient to get
consensus!

@dlongley does this mean we do the same type of calculation done here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L113

Which involves getting the `latestBlock` and counting the votes that were cast on the last block?  As here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L113

**Comment by dlongley** [comment]
It involves getting twoThirds majority of the *electors* not the previous votes. Just get the current block electors (or pass it in) and use the length of it in the twoThirds function.

We should probably add this check wherever we're adding manifests (hopefully there's just one spot we can put this?) so we just make sure a manifest is never added that can't possibly have consensus.
