### ISSUE TITLE
Add additional document/comment regarding recovery electors

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#133]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/f07c999b71ae9af3503003b1f06fd5f4e181a1a7/lib/election.js#L212-L216

Add explanation that the requirement that `recoveryElectors` be a subset of `electors` is required to ensure that there are no forks.

**Comment by dlongley** [comment]
Recovery mode has been removed.
