### ISSUE TITLE
Change `recoveryElectors` to `failureDetectors`

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#134]
Everywhere it's used in code.  e.g. https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/9a4ae1759ee5f9d033c7ca96f2cc6dd5242bc080/lib/consensus.js#L51-L52

`failureDetectors` is more accurate and less confusing.

**Comment by dlongley** [comment]
Recovery mode removed.
