### ISSUE TITLE
Implement basisBlockHeight/basisHash for operations and regular events

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#135]
A node must record what state it was in when it originally validated operations.  This is in order that other nodes may validate the operations using the same state.  

We might use use the term `basisBlockHeight` or `basisHash`.  `basisHash` is desirable because it works with or without the concept of a `block`.  Here's a description of each:
1. `basisBlockHeight` the latest blockHeight 
2. `basisHash` this could be one of two values:
  a. the hash of the *last* event included in the latest block.  This is the event for a given `meta.blockHeight` that has the highest `meta.blockOrder` value.
  b. the hash of the most recent merge event for the creator that has reached consensus.

`basisFoo` will be used in place of one of the above options.

In order to accomplish this:
1. `basisFoo` will be recorded in the *metaData* of incoming operations.
2. When regular events are created they must be batched by `basisFoo`.  That is, all operations included in a regular event must have the same `basisFoo` value.
3. Regular events will record `basisFoo` in their body.
4. No change are made to the creation of merge events.
5. When processing incoming gossip, nodes will use the `basisFoo` value in regular events to inform the state of the validation process.

**Comment by mattcollier** [comment]
It was decided that `basisBlockHeight` will be used.  Here is a brief summary of the reasoning.

We believe that all consensus methods will have *some* abstraction that represents a group of events that reach consensus at the same time.  Continuity refers to this abstraction as blocks.  A block generally and `basisBlockHeight` is just a shorthand way of referring to a collection of events.

**Comment by dlongley** [comment]
This was implemented, closing.
