### ISSUE TITLE
Reject votes with more than X number of recommended electors

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#14]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L221

TODO: reject votes with more than X number of recommended electors
based on continuity config

@dlongley this needs explanation.

**Comment by dlongley** [comment]
The continuity config should be able to indicate a maximum number of recommended electors. If a vote comes in with more than the max, the vote should be rejected. For now, we should just limit the number of recommended electors to the maximum number of electors or the hard coded max of 10 as seen here:

https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L110

```js
const electorCount = results.config.electorCount || 10;
```

**Comment by mattcollier** [comment]
@dlongley the `electorCount` configuration is bedrock configuration parameter, not a part of the webLedgerConfiguration?  If that's the case, it sounds like it would be easy to accidentally setup a ledger server with an `electorCount` setting that is incompatible with the other servers?

**Comment by dlongley** [comment]
`results.config` is the web ledger config, isn't it?
