### ISSUE TITLE
Send votes we know about to peer to optimize

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#15]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L309

TODO: send votes we know about to peer to optimize

@dlongley needs explanation.

**Comment by dlongley** [comment]
In the same way that we get events from the peer and then send them any events they don't have, we should do the same with votes. This means adding a `POST votes` end point to `server.js` and adding code to send votes that aren't in `status.election` to the peer. The code should be close to a copy/paste of what's going on in the event section.

We can deprioritize this particular issue behind some of the lower hanging fruit issues first if necessary.

**Comment by dlongley** [comment]
No longer applicable.
