### ISSUE TITLE
Do not log FULL axios errors to log files

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#159]
Axios errors are extremely verbose.  Need to figure out a way to capture the meaningful parts of the error message for logs.  The `apisauce` (axios wrapper) module might be helpful here.

Example error: https://gist.github.com/gannan08/8644b4aa14c50a7219b30c0f77b9fb2d

**Comment by dlongley** [comment]
Axios has been removed. Closing.
