### ISSUE TITLE
If the vote manifest is already stored, skip certification

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#16]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L212

TODO: should be able to see if the vote manifest is already stored
and skip certification if so

@dlongley does this mean...

That somewhere before [L215](https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L215) 

1. Hash the `vote`
2. Use the new `exists` API (in PR) to check for existence of the vote.
3. If it does exist, return early (inside the `async.each`), skipping the `_verifyVote` and `api._storage` steps?

**Comment by dlongley** [comment]
Yes, that's what it means. We can move the hasher code that is currently called after vote verification to the top of the function and use it to do the `exists` call. Then, return early if it exists -- otherwise verify and then use that precomputed hash value to store the vote.
