### ISSUE TITLE
Should wait some period of time before communicating again

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#17]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L208

TODO: should wait some period of time before communicating again
with the electors to allow gossip/votes to settle?

@dlongley needs explanation.

**Comment by dlongley** [comment]
Let's add a config value (not to the ledger, but to the module) of, for now, 10 seconds, to wait until running `loop` again. If there's an error (if `err` is true https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L213) we should loop immediately and not wait. If we're just not an elector, we should wait the full time. We should also wait before calling loop down here:

https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L241

We'll need to experiment with the performance characteristics of doing this. It's meant to reduce the amount of wasted traffic to give nodes a chance to make decisions ... and we're likely going to need to tweak it, but we can't do that until it's at least implemented. So let's implement it and set it to 10 seconds for now.
