### ISSUE TITLE
If the voter isn't an elector, we could also set the status here to 'decideEvents'

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#18]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/server.js#L302

TODO: if the voter isn't an elector, we could also set the status
here to 'decideEvents' to allow for propagation of votes
via all peers on the network

@dlongley needs explanation.

**Comment by dlongley** [comment]
So we want to change the conditional at the top to pass under these conditions:

1. If there are votes in the events election AND...
1.1. (The voter has voted in the events election OR the roll call election) OR
1.2. The voter is not an elector (check this last, it requires a database hit and some work).
