### ISSUE TITLE
If there were no electors chosen or insufficient electors, add electors from config

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#19]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L176

TODO: if there were no electors chosen or insufficient electors,
add electors from config

@dlongley needs explanation.

**Comment by dlongley** [comment]
This currently can't happen so I think we can punt for now. The place where it could potentially happen is when switching configs. Presumably, the new config would be approved under the old rules, which means that there would be no previous voters from which to draw for the elector population. In that case, we need the config to specify them -- and we would use them here.

Let's keep this issue open to implement in the future. To implement it, we just need to add a `recommendedElector` to the ledger config and use it where the TODO is.

**Comment by dlongley** [comment]
No longer applicable.
