### ISSUE TITLE
Implement _getPeers?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#2]
We have a TODO about implementing this function here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L112

Is this still needed?

**Comment by dlongley** [comment]
Yes, this has to do with obtaining extra peers to gossip with from an external list (i.e. one specified in some ledger agent info or elsewhere). It's useful for bootstrapping a continuity-based ledger when the peers listed in the initial set of N blocks can no longer be contacted, but some other current peers have the original (signed and valid) history.

**Comment by dlongley** [comment]
Closing out of date.
