### ISSUE TITLE
Upgrade to `bedrock-mongodb >= 7.0.0`

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-ledger-consensus-continuity#201]
This branch contains the work:
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/tree/mongo-version-3

Steps needed:

- [ ] check out the `mongo-version-3` branch
- [ ] rm -rf node_modules in root and test dirs
- [ ] check dependencies and peerDepencies in the root project
- [ ] check deps and peerDeps in the test project
- [ ] `npm i` in both root and test
- [ ] look for all calls on `collection` or `collections`
- [ ] change all deprecated calls on on `insert` or `update`
    - `insert` becomes `insertOne` `insertMany`
    - `update` becomes `updateOne` or `updateMany`
- [ ] check all uses of `collection` against the latest [mongo collection api](http://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html)
- [ ] double check all uses of `bedrock-mongodb` against the [latest api](http://mongodb.github.io/node-mongodb-native/3.6/api/index.html)
- [ ] `collection.s.name` has been deprecated and returns undefined use `collectionName` instead
- [ ] update test project to pass using latest libraries (this is where I was stuck)
- [ ] update the `before` and `beforeEach` methods in the tests to use the newer async methods (there are tests that can used as examples for this)
- [ ] Add a changelog for all changes that will probably be a major change
- [ ] Make a DRAFT PR
- [ ] Check to ensure other ledger related libraries have been updated.

**Comment by dlongley** [comment]
This is done, closing.
