### ISSUE TITLE
Include all current electors 

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#23]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/election.js#L423

FIXME: include all current electors (should filter this by those
that voted in the last election so we don't recommend those that
aren't participating)

**Comment by mattcollier** [comment]
The `_recommendElectors` helper here is called in only one place in [_createFirstRoundEventVote](http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/966a4005cba9d441b3d5473bf8a64b54b4e1ffc4/lib/election.js#L347-L348)

And have found that in the `Multinode` consensus test, that `_recommendElectors` is run only once during the entire test.  I am remembering now that we're doing some special things in the test suite to bootstrap the electors.  I'll investigate further.

**Comment by dlongley** [comment]
To build our list of recommended electors, we should first grab the latest block (which we're doing in the section below). Then add in everyone who voted. Then add in our event peers. Then add in from the previous electors.

All the while, limiting the recommended electors to the max elector count in the config or the hard coded `10` if no max is set. Also, we should ensure our list is unique.
