### ISSUE TITLE
Tracking issue: replace axios with http-client

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#245]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/client.js#L7

`axios` dep is presently causing security warnings.

**Comment by aljones15** [comment]
@mattcollier I believe this can be closed now. @gannan08 just double checking.

**Comment by dlongley** [comment]
Addressed, closing.
