### ISSUE TITLE
Explore modifications to voter selection algorithm

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#3]
Additional modifications to the voter selection sorting algorithm that present various ledger security properties should be considered:

1. "voter age" - e.g. must have been recommended to vote for X consecutive blocks or X blocks ago.
2. "voter frequency" - e.g. must not have voted in the last X elections (or vice versa).
3. ...?

Also, note that the use of recommended voters could be problematic for ledger security; a replay of the history of the ledger with subtle changes to include additional voters from the start of the genesis block could enable changes to the voting population in the future. This would only affect nodes that are resyncing. Consider potential remedies or arguments for why this is acceptable.

**Comment by mattcollier** [comment]
@dlongley is this still relevant?

**Comment by dlongley** [comment]
No, closing.
