### ISSUE TITLE
Do a more robust check to ensure that the peer is up-to-date

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#36]
http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/b1a31b0c112f54c85a1206105ec1a92276275dd6/lib/election.js#L493-L494

TODO: do a more robust check to ensure that the peer is up-to-date 
with the current blockHeight (block status phase is `consensus`)

**Comment by dlongley** [comment]
This code is about trying to verify that the entity that signed an event is *actually* a Contintuity2017 peer that is participating on the ledger. So we want a "more robust" check than just asking the potential peer for the block status for blockheight zero. We should see if they are "up-to-date" with the latest block height, etc.

**Comment by dlongley** [comment]
Perhaps a better check would be to do N block status checks at random. We want a "quick enough" check that shows that the peer really is mirroring the ledger and participating.

**Comment by dlongley** [comment]
No longer applicable.
