### ISSUE TITLE
Do we really want/need to store *all* votes 

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#37]
http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/b1a31b0c112f54c85a1206105ec1a92276275dd6/lib/election.js#L616-L617

TODO: do we really want/need to store *all* votes or just the ones
  from the winning round? what's the attack?

**Comment by dlongley** [comment]
No longer applicable.
