### ISSUE TITLE
How does returning `consensus` as a phase help?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#38]
http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/b1a31b0c112f54c85a1206105ec1a92276275dd6/lib/worker.js#L400-L403

TODO: how does returning `consensus` as a phase help? Do we only need
the election phase -- after which the node should automatically detect
and verify consensus and avoid talking to other nodes?

**Comment by dlongley** [comment]
It is helpful for a number of reasons including deciding whether or not to tell the peer about any information you have that is now erroneous. It helps optimize a number of other things. Let's remove the TODO.

**Comment by dlongley** [comment]
In fact, let's remove that entire old function w/notes.

**Comment by mattcollier** [comment]
only action on this is to remove commented code:

https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/b1a31b0c112f54c85a1206105ec1a92276275dd6/lib/worker.js#L328-L455

**Comment by dlongley** [comment]
Will be addressed via #56.

**Comment by dlongley** [comment]
Fixed by #56.
