### ISSUE TITLE
How to handle key rotation?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#39]
http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/b1a31b0c112f54c85a1206105ec1a92276275dd6/lib/voterStorage.js#L67-L68

TODO: how to handle key rotation?

**Comment by dlongley** [comment]
There will be no URL or key rotation for peers, rather a new peer needs to be created if keys must be changed and once peer IDs become did:keys, URLs will be fully decoupled and can change as needed.
