### ISSUE TITLE
Verify node signature on each event?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#40]
http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/b1a31b0c112f54c85a1206105ec1a92276275dd6/lib/election.js#L746-L747

TODO: verify node signature on each event? (not in alpha version)

**Comment by dlongley** [comment]
I'm marking this as MVP temporarily because we need to figure out what we're doing first -- before we can decide if we can push it off.

**Comment by dlongley** [comment]
We're doing this in `_getEventPeers`; see #36.

**Comment by dlongley** [comment]
We should really look into doing PoW signatures as well as a better measure of a node's willingness to become an elector. Doing a simple RSA signature, etc. isn't as strong a proof.

**Comment by dlongley** [comment]
To be clear, we're doing this signature check in #36 -- and the reason for node signatures on events is for them to distinguish themselves as good future potential electors by participating in the network.

**Comment by dlongley** [comment]
Moving to the future as we can incrementally improve our verification that peers really are Continuity2017 peers -- and improve/discuss/implement different signature/proof types dynamically.

**Comment by dlongley** [comment]
This relates to the old design and is no longer applicable.
