### ISSUE TITLE
Was expecting to have to check full URL

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#41]
http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/b1a31b0c112f54c85a1206105ec1a92276275dd6/lib/election.js#L479-L482

TODO: was expecting to have to check full URL:
  `https://w3id.org/webledger#Continuity2017Peer`... but doesn't
  seem to be the case with what comes back from jsigs

**Comment by dlongley** [comment]
No longer applicable.
