### ISSUE TITLE
Manifest Storage

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#47]
http://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/e7a893b1f0b407e5e24c59021e55e3bdda0c52a4/lib/election.js#L913-L931

Couple of concerns here:  

First, why are manifest id's hashes of *only* the items list.  Why are we not dealing with manifests like we do all other hashed documents in the system by storing the hash in `meta.manifestHash` for example.

Second, since the hash *only* includes `items` and does not include the blockHeight (or `type`) that a manifest with the same items, but different `blockHeight` might find its way into the system and gum up the works.  For that matter might it be legitimate for the same items to be found in manifests with different `blockHeight` values?

**Comment by dlongley** [comment]
We no longer use manifests.
