### ISSUE TITLE
Make sure `Events` election topic is certified BEFORE roll-call

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#6]
TODO: make sure `Events` election topic is certified *BEFORE*
roll-call because we depend on the votes for events to exist
in the database (and they only get there if they are certified)

https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L310

**Comment by mattcollier** [comment]
@dlongley need more guidance on this one.

**Comment by dlongley** [comment]
All this means is that we can't blindly run the "eachSeries" and assume the order of `status.election` will be `[events election, roll call election]`. It could be swapped for some reason. So we should sort `status.election` by `election.topic` with `Events` coming before `RollCall` before running `eachSeries`.
