### ISSUE TITLE
Add a test that has continuity worker fail after marking some events as reached consensus

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#63]

**Comment by mattcollier** [comment]
This test is to ensure that the node can properly reach consensus after events were updated with consensus flag but *before* the block was written: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L381-L453

**Comment by dlongley** [comment]
No longer applicable.
