### ISSUE TITLE
Switch peer keys over to Ed25519

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#65]
We should switch to Ed25519 as soon as we can (prior to testnet launch preferably) for peer keys. There's no compatibility need for RSA and we only need a node.js implementation (no need for a browser implementation). Essentially, there's no reason not to switch, only advantages.

**Comment by mattcollier** [comment]
This has already been implemented, but I have just discovered a wrinkle.  I believe the plan was to utilized HTTP Signatures to secure the gossip endpoints to allow requests only from authorized peers.

I found this PR which you may be familiar with: https://github.com/joyent/node-http-signature/pull/58 and https://github.com/digitalbazaar/request/commit/f3cdbc2cb7a19c8363c15566b0a8171066eedddc

It does not appear that there is any support for ed25519 in the http-signatures module.  

Does something need to be done that works with the RequestSigner API?

**Comment by dlongley** [comment]
Yeah, I think we'll have to use the RequestSigner API and create the headers separately and pass them manually to request (or `r2`).

**Comment by mattcollier** [comment]
ed25519 has been implemented in continuity.  Added issue for upgrading HTTPSignature support here: https://github.com/digitalbazaar/bedrock-passport/issues/19
