### ISSUE TITLE
Duplicates in `order`.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#67]
I have discovered that `order` still contains duplicates which are clearly visible if you add logging as here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/compare/orderDuplicates

**Comment by dlongley** [comment]
Ok, I think I have a fix.

**Comment by dlongley** [comment]
Fixed via 70ef4ee200dfbd9ba23bc332f74d864bb562c444.
