### ISSUE TITLE
Excessive error reporting when network is reset

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-ledger-consensus-continuity#86]
When a blockchain network, such as a testnet, using continuity is reset... it may be that other individual/organizations are running older nodes. The old nodes still contact the genesis node that has been reset, as well as other peers in the network, to get new events. Clearly, what they're connecting to is a different blockchain network with the same network ID, at which point they start randomly trying to sync. One of the first things they do is try to get voter IDs, which no longer exist on the reset network. They do this over and over again, rapidly filling up the error logs on the new genesis node and new peer nodes resulting in GBs written over the course of a day. This is an excerpt of the error:

```
  "error": {
    "message": "Voter information not found for the given ledger node.",
    "type": "NotFoundError",
    "details": {
      "httpStatusCode": 400,
      "public": true,
      "voterId": "https://example.org/consensus/continuity2017/voters/D3cuzrVyHTm7MMN6maAscPmD7x7spZxC45XT3vkWDT6c"
    },
    "cause": null,
    "stack": {
      "message": "NotFoundError: Voter information not found for the given ledger node.",
      "at": [
        "collection.findOne (.../node_modules/bedrock-ledger-consensus-continuity/lib/storage-voters.js:156:23)",
```

Can we:

1. Catch  this error and do something about it that doesn't spam the log as much. I expect this to be a fairly regular occurrence in development and testnet mode.
2. Implement a back-off algorithm of some kind so a large network doesn't DDoS their peer nodes that they've de-sync'd from?

**Comment by dlongley** [comment]
No longer applies with the new design. Closing.
