### ISSUE TITLE
Certify votes

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#9]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/worker.js#L309

1. TODO: send votes we know about to peer to optimize
2. TODO: validate `status.election`

Due to a glitch in the reporting tool, I'm not sure which of these two to-dos (or possibly both) we want to address.  Whatever the case, @dlongley, more explanation is needed here.

**Comment by dlongley** [comment]
We already have another issue for sending the votes (#15) so let's make this one about validating `status.election`. And we want to do that validation first, it's more critical than optimizing.

**Comment by dlongley** [comment]
`status.election` is an array with one or two election results in it. Each election result has a topic and some votes in `electionResult` (I think). Need to validate that and use a "vote validator" (which we also need to create) on each vote. That's what needs to be done here... standard validation.

**Comment by mattcollier** [comment]
Needs to address: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/client.js#L48 as well
