### ISSUE TITLE
Revise node public key handling

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-consensus-continuity#90]
Summary: Public key is to be derived from the voter ID.  Therefore there is no need to fetch/cache/record public keys for voters anymore.  This includes the removal of voter public key data from blocks.

Work on this has begun here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/compare/public-key-fix

**Comment by dlongley** [comment]
Addressed by #110.
