### ISSUE TITLE
Add flag to `getMany` to receive events as JSON, instead of parsed

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#91]
This would allow the JSON to be passed straight through to clients requesting events without the extra parse + reserialize step that we're currently doing.

**Comment by mattcollier** [comment]
What extra step are you referring to?

**Comment by dlongley** [comment]
Maybe I should have filed this on bedrock-ledger-storage-mongodb ... or maybe it's not possible. We're pulling data out of mongo ... and immediately reserializing it to send it to a client. It seems like there's an extra parse + serialize that could be potentially skipped. Perhaps the solution is to store the JSON stringified data and just pull that out and send it.

**Comment by dlongley** [comment]
Closing as no longer relevant.
