### ISSUE TITLE
Limit number of event hashes requested and permitted to be requested during gossip

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#92]
https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/server.js#L136-L137

**Comment by mattcollier** [comment]
This is effectively handled during gossip by the `maxDepth` setting here: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/lib/config.js#L63

but I can see that this is a potential DOS vector, so a configurable hard limit seems appropriate.

**Comment by dlongley** [comment]
We also need to have a strategy around limiting the number of heads to be requested/responded to to allow for the network of peers (non-witnesses primarily) to grow unbounded.

**Comment by dlongley** [comment]
This has been addressed by using `localEventNumber` and a gossip `cursor` ... and limiting the maximum number of events that can be sent during gossip.
