### ISSUE TITLE
Consider changing consensus worker pool to use node 10.x threads API

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#93]
Or maybe the worker pool lib will get updated to do this for us.

**Comment by mattcollier** [comment]
First, I note that as of node 10.9.0, the worker thread API is still experimental.

From what I can tell, the big new thing here is the ability to have a shared ArrayBuffer between processes.  This is similar to the way that WASM works with shared linear memory.  So the big win is when there is a binary data payload.  Maybe a thread is applying a filter to JPG image or something along those lines.  So one could potentially divide the image ArrayBuffer into 8 pieces and put 8 threads onto processing their piece of the image. 

In our case, we're dealing with objects/maps and from what I can tell there are no gains to be had here.

Along these lines, I have done some experimentation with serializing objects into other formats such as protobuffers as here: https://github.com/digitalbazaar/loop-bench/blob/master/index3.js

If the javascript object has a well defined type structure, a descriptor can be created like this: https://github.com/digitalbazaar/loop-bench/blob/master/continuity-event.json

The protobuf encoder is marginally faster than JSON.stringify, and the protobuf decoder blows the doors off JSON.parse.  This is great if you can send protocol buffers over the wire or some such.

The test I was doing had to do with getting objects into and out of redis.  To redis, everything is a string, and to work properly, the protobuf data had to be base64 encoded and by the time you do that additional encoding, the gains from using protobuf in the first place are lost.

@dlongley are you seeing an opportunity here that I am not aware of?

Here's some research articles:
https://medium.com/dailyjs/threads-in-node-10-5-0-a-practical-intro-3b85a0a3c953
https://www.npmjs.com/package/node-threadpool#examples
https://stackoverflow.com/questions/51053222/nodejs-worker-threads-shared-object-store
https://stackoverflow.com/questions/25519325/share-objects-in-nodejs-between-different-instances

**Comment by dlongley** [comment]
Closing this, we rely on the workerPool to handle this and we may even be removing that anyway.
