### ISSUE TITLE
Consider renaming voterId to peerId or nodeId to avoid confusion

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-ledger-consensus-continuity#94]
Not every peer/node is a voter. Using `nodeId` might be confusing though -- as it could be confused with `ledgerNodeId`.

**Comment by mattcollier** [comment]
It has been decided that all references to 'voterId` should be replaced with `peerId`.

**Comment by dlongley** [comment]
This has been done, closing.
